/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_library_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vendors */
        get: operations["list_vendors_api_v1_library_vendors_get"];
        put?: never;
        /** Create Vendor */
        post: operations["create_vendor_api_v1_library_vendors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/vendors/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vendor */
        get: operations["get_vendor_api_v1_library_vendors__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/vendors/{vendor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Vendor */
        delete: operations["delete_vendor_api_v1_library_vendors__vendor_id__delete"];
        options?: never;
        head?: never;
        /** Update Vendor */
        patch: operations["update_vendor_api_v1_library_vendors__vendor_id__patch"];
        trace?: never;
    };
    "/api/v1/library/vendors/{vendor_slug}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_v1_library_vendors__vendor_slug__products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_v1_library_vendors__vendor_slug__products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/vendors/{vendor_slug}/products/{product_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_library_vendors__vendor_slug__products__product_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Product */
        delete: operations["delete_product_api_v1_library_products__product_id__delete"];
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_api_v1_library_products__product_id__patch"];
        trace?: never;
    };
    "/api/v1/library/products/{product_id}/log_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Log Types */
        get: operations["list_log_types_api_v1_library_products__product_id__log_types_get"];
        put?: never;
        /** Create Log Type */
        post: operations["create_log_type_api_v1_library_products__product_id__log_types_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/log_types/{log_type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Log Type */
        get: operations["get_log_type_api_v1_library_log_types__log_type_id__get"];
        put?: never;
        post?: never;
        /** Delete Log Type */
        delete: operations["delete_log_type_api_v1_library_log_types__log_type_id__delete"];
        options?: never;
        head?: never;
        /** Update Log Type */
        patch: operations["update_log_type_api_v1_library_log_types__log_type_id__patch"];
        trace?: never;
    };
    "/api/v1/library/log_types/{log_type_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Log Type */
        post: operations["publish_log_type_api_v1_library_log_types__log_type_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/log_types/{log_type_id}/parse_rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Parse Rules */
        get: operations["list_parse_rules_api_v1_library_log_types__log_type_id__parse_rules_get"];
        put?: never;
        /** Create Parse Rule Draft */
        post: operations["create_parse_rule_draft_api_v1_library_log_types__log_type_id__parse_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/parse_rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Parse Rule */
        get: operations["get_parse_rule_api_v1_library_parse_rules__rule_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Parse Rule */
        patch: operations["update_parse_rule_api_v1_library_parse_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/library/parse_rules/{rule_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote Parse Rule */
        post: operations["promote_parse_rule_api_v1_library_parse_rules__rule_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/log_types/{log_type_id}/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace Log Type Fields */
        put: operations["replace_log_type_fields_api_v1_library_log_types__log_type_id__fields_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/log_types/{log_type_id}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Samples */
        get: operations["list_samples_api_v1_library_log_types__log_type_id__samples_get"];
        put?: never;
        /** Create Sample */
        post: operations["create_sample_api_v1_library_log_types__log_type_id__samples_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/samples/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Sample */
        delete: operations["delete_sample_api_v1_library_samples__sample_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/log_types/{log_type_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log Type Stats */
        get: operations["log_type_stats_api_v1_library_log_types__log_type_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/products/{vendor_slug}/{product_slug}/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product Coverage */
        get: operations["product_coverage_api_v1_library_products__vendor_slug___product_slug__coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyzer/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse */
        post: operations["parse_api_v1_analyzer_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyzer/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fixtures */
        get: operations["list_fixtures_api_v1_analyzer_fixtures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyzer/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check */
        post: operations["check_api_v1_analyzer_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyzer/match-availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match Availability */
        get: operations["match_availability_api_v1_analyzer_match_availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyzer/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match */
        post: operations["match_api_v1_analyzer_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckRequest */
        CheckRequest: {
            /** Vrl Code */
            vrl_code: string;
            /**
             * Engine Version
             * @default 0.32
             * @enum {string}
             */
            engine_version: "0.25" | "0.32";
        };
        /** CheckResponse */
        CheckResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "ok" | "compile_error";
            /**
             * Engine
             * @enum {string}
             */
            engine: "0.25" | "0.32";
            /** Compile Error */
            compile_error?: string | null;
        };
        /** CoverageLogType */
        CoverageLogType: {
            /**
             * Log Type Id
             * Format: uuid
             */
            log_type_id: string;
            /** Sparkline */
            sparkline: number[];
            /** Success Rate Avg */
            success_rate_avg: number;
            /** Volume */
            volume: number;
        };
        /** DataResponse[CheckResponse] */
        DataResponse_CheckResponse_: {
            data: components["schemas"]["CheckResponse"];
        };
        /** DataResponse[FixtureListResponse] */
        DataResponse_FixtureListResponse_: {
            data: components["schemas"]["FixtureListResponse"];
        };
        /** DataResponse[LogTypeDetail] */
        DataResponse_LogTypeDetail_: {
            data: components["schemas"]["LogTypeDetail"];
        };
        /** DataResponse[LogTypeRead] */
        DataResponse_LogTypeRead_: {
            data: components["schemas"]["LogTypeRead"];
        };
        /** DataResponse[LogTypeStats] */
        DataResponse_LogTypeStats_: {
            data: components["schemas"]["LogTypeStats"];
        };
        /** DataResponse[MatchAvailabilityResponse] */
        DataResponse_MatchAvailabilityResponse_: {
            data: components["schemas"]["MatchAvailabilityResponse"];
        };
        /** DataResponse[MatchResponse] */
        DataResponse_MatchResponse_: {
            data: components["schemas"]["MatchResponse"];
        };
        /** DataResponse[ParseResponse] */
        DataResponse_ParseResponse_: {
            data: components["schemas"]["ParseResponse"];
        };
        /** DataResponse[ParseRuleRead] */
        DataResponse_ParseRuleRead_: {
            data: components["schemas"]["ParseRuleRead"];
        };
        /** DataResponse[ProductCoverage] */
        DataResponse_ProductCoverage_: {
            data: components["schemas"]["ProductCoverage"];
        };
        /** DataResponse[ProductDetail] */
        DataResponse_ProductDetail_: {
            data: components["schemas"]["ProductDetail"];
        };
        /** DataResponse[ProductRead] */
        DataResponse_ProductRead_: {
            data: components["schemas"]["ProductRead"];
        };
        /** DataResponse[SampleLogRead] */
        DataResponse_SampleLogRead_: {
            data: components["schemas"]["SampleLogRead"];
        };
        /** DataResponse[UserRead] */
        DataResponse_UserRead_: {
            data: components["schemas"]["UserRead"];
        };
        /** DataResponse[VendorRead] */
        DataResponse_VendorRead_: {
            data: components["schemas"]["VendorRead"];
        };
        /** DataResponse[dict] */
        DataResponse_dict_: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** DataResponse[list[FieldSchemaRead]] */
        DataResponse_list_FieldSchemaRead__: {
            /** Data */
            data: components["schemas"]["FieldSchemaRead"][];
        };
        /** DataResponse[list[LogTypeRead]] */
        DataResponse_list_LogTypeRead__: {
            /** Data */
            data: components["schemas"]["LogTypeRead"][];
        };
        /** DataResponse[list[OverviewVendorGroup]] */
        DataResponse_list_OverviewVendorGroup__: {
            /** Data */
            data: components["schemas"]["OverviewVendorGroup"][];
        };
        /** DataResponse[list[ParseRuleRead]] */
        DataResponse_list_ParseRuleRead__: {
            /** Data */
            data: components["schemas"]["ParseRuleRead"][];
        };
        /** DataResponse[list[ProductRead]] */
        DataResponse_list_ProductRead__: {
            /** Data */
            data: components["schemas"]["ProductRead"][];
        };
        /** DataResponse[list[SampleLogRead]] */
        DataResponse_list_SampleLogRead__: {
            /** Data */
            data: components["schemas"]["SampleLogRead"][];
        };
        /** DataResponse[list[VendorRead]] */
        DataResponse_list_VendorRead__: {
            /** Data */
            data: components["schemas"]["VendorRead"][];
        };
        /** EngineUsage */
        EngineUsage: {
            /**
             * Engine Version
             * @enum {string}
             */
            engine_version: "0.25" | "0.32";
            /** Count */
            count: number;
        };
        /** FieldSchemaBulkReplace */
        FieldSchemaBulkReplace: {
            /** Fields */
            fields: components["schemas"]["FieldSchemaItem"][];
        };
        /** FieldSchemaItem */
        FieldSchemaItem: {
            /** Field Name */
            field_name: string;
            /**
             * Field Type
             * @enum {string}
             */
            field_type: "string" | "int" | "float" | "bool" | "timestamp" | "ip" | "object" | "array";
            /** Description */
            description?: string | null;
            /**
             * Is Required
             * @default false
             */
            is_required: boolean;
            /**
             * Is Identifier
             * @default false
             */
            is_identifier: boolean;
            /** Example Value */
            example_value?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** FieldSchemaRead */
        FieldSchemaRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Log Type Id
             * Format: uuid
             */
            log_type_id: string;
            /** Field Name */
            field_name: string;
            /**
             * Field Type
             * @enum {string}
             */
            field_type: "string" | "int" | "float" | "bool" | "timestamp" | "ip" | "object" | "array";
            /** Description */
            description: string | null;
            /** Is Required */
            is_required: boolean;
            /** Is Identifier */
            is_identifier: boolean;
            /** Example Value */
            example_value: string | null;
            /** Sort Order */
            sort_order: number;
        };
        /** FixtureItem */
        FixtureItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Vrl */
            vrl: string;
            /** Logs */
            logs: string;
            /**
             * Engine
             * @enum {string}
             */
            engine: "0.25" | "0.32";
        };
        /** FixtureListResponse */
        FixtureListResponse: {
            /** Fixtures */
            fixtures: components["schemas"]["FixtureItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LogTypeCounts */
        LogTypeCounts: {
            /** Total */
            total: number;
            /** Published */
            published: number;
            /** Draft */
            draft: number;
        };
        /** LogTypeCreate */
        LogTypeCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
            /**
             * Format
             * @enum {string}
             */
            format: "syslog" | "json" | "cef" | "leef" | "csv" | "other";
            /** Transport */
            transport?: ("syslog_udp" | "syslog_tcp" | "http" | "file" | "other") | null;
            /** Description */
            description?: string | null;
        };
        /**
         * LogTypeDetail
         * @description LogType + 內嵌 fields / current_parse_rule / samples（用於 detail endpoint）。
         */
        LogTypeDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Format
             * @enum {string}
             */
            format: "syslog" | "json" | "cef" | "leef" | "csv" | "other";
            /** Transport */
            transport: ("syslog_udp" | "syslog_tcp" | "http" | "file" | "other") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published";
            /**
             * Source
             * @constant
             */
            source: "manual";
            /** Current Parse Rule Id */
            current_parse_rule_id: string | null;
            /** Description */
            description: string | null;
            /** Published At */
            published_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Fields */
            fields: components["schemas"]["FieldSchemaRead"][];
            current_parse_rule: components["schemas"]["ParseRuleRead"] | null;
            /** Samples */
            samples: components["schemas"]["SampleLogRead"][];
        };
        /** LogTypeRead */
        LogTypeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Format
             * @enum {string}
             */
            format: "syslog" | "json" | "cef" | "leef" | "csv" | "other";
            /** Transport */
            transport: ("syslog_udp" | "syslog_tcp" | "http" | "file" | "other") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published";
            /**
             * Source
             * @constant
             */
            source: "manual";
            /** Current Parse Rule Id */
            current_parse_rule_id: string | null;
            /** Description */
            description: string | null;
            /** Published At */
            published_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LogTypeStats */
        LogTypeStats: {
            /** Enabled */
            enabled: boolean;
            /** Range Days */
            range_days: number;
            /** Timeline */
            timeline: components["schemas"]["TimelinePoint"][];
            /** Engine Usage */
            engine_usage: components["schemas"]["EngineUsage"][];
            totals: components["schemas"]["StatsTotals"];
        };
        /** LogTypeUpdate */
        LogTypeUpdate: {
            /** Name */
            name?: string | null;
            /** Format */
            format?: ("syslog" | "json" | "cef" | "leef" | "csv" | "other") | null;
            /** Transport */
            transport?: ("syslog_udp" | "syslog_tcp" | "http" | "file" | "other") | null;
            /** Description */
            description?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MatchAvailabilityResponse */
        MatchAvailabilityResponse: {
            /** Available */
            available: boolean;
        };
        /** MatchCandidate */
        MatchCandidate: {
            /** Vendor Slug */
            vendor_slug: string;
            /** Product Slug */
            product_slug: string;
            /**
             * Log Type Id
             * Format: uuid
             */
            log_type_id: string;
            /** Log Type Name */
            log_type_name: string;
            /** Confidence */
            confidence: number;
            /** Reason */
            reason: string;
        };
        /** MatchRequest */
        MatchRequest: {
            /** Raw Log */
            raw_log: string;
            /**
             * Top K
             * @default 3
             */
            top_k: number;
        };
        /** MatchResponse */
        MatchResponse: {
            /** Candidates */
            candidates: components["schemas"]["MatchCandidate"][];
        };
        /** OverviewProduct */
        OverviewProduct: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive";
            log_type_counts: components["schemas"]["LogTypeCounts"];
            /** Is Empty */
            is_empty: boolean;
        };
        /** OverviewVendor */
        OverviewVendor: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Logo Url */
            logo_url: string | null;
        };
        /** OverviewVendorGroup */
        OverviewVendorGroup: {
            vendor: components["schemas"]["OverviewVendor"];
            /** Products */
            products: components["schemas"]["OverviewProduct"][];
        };
        /** ParseRequest */
        ParseRequest: {
            /** Vrl Code */
            vrl_code: string;
            /** Logs */
            logs: string[];
            /**
             * Engine Version
             * @default 0.32
             * @enum {string}
             */
            engine_version: "0.25" | "0.32";
            /** Log Type Id */
            log_type_id?: string | null;
            /** Parse Rule Id */
            parse_rule_id?: string | null;
        };
        /** ParseResponse */
        ParseResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "ok" | "compile_error" | "empty";
            /**
             * Engine
             * @enum {string}
             */
            engine: "0.25" | "0.32";
            /** Compile Error */
            compile_error?: string | null;
            summary?: components["schemas"]["ParseSummary"] | null;
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["ParseResultItem"][];
        };
        /** ParseResultItem */
        ParseResultItem: {
            /** Index */
            index: number;
            /** Input */
            input: string;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "error";
            /** Output */
            output?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /** ParseRuleCreate */
        ParseRuleCreate: {
            /** Vrl Code */
            vrl_code: string;
            /**
             * Engine Version
             * @enum {string}
             */
            engine_version: "0.25" | "0.32";
            /** Notes */
            notes?: string | null;
        };
        /** ParseRuleRead */
        ParseRuleRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Log Type Id
             * Format: uuid
             */
            log_type_id: string;
            /** Version */
            version: number;
            /** Vrl Code */
            vrl_code: string;
            /**
             * Engine Version
             * @enum {string}
             */
            engine_version: "0.25" | "0.32";
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published" | "archived";
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ParseRuleUpdate */
        ParseRuleUpdate: {
            /** Vrl Code */
            vrl_code?: string | null;
            /** Engine Version */
            engine_version?: ("0.25" | "0.32") | null;
            /** Notes */
            notes?: string | null;
        };
        /** ParseSummary */
        ParseSummary: {
            /** Total */
            total: number;
            /** Success */
            success: number;
            /** Error */
            error: number;
        };
        /** ProductCoverage */
        ProductCoverage: {
            /** Enabled */
            enabled: boolean;
            /** Range Days */
            range_days: number;
            /** Log Types */
            log_types: components["schemas"]["CoverageLogType"][];
        };
        /** ProductCreate */
        ProductCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
            /** Version */
            version?: string | null;
            /** Description */
            description?: string | null;
            /** Deploy Type */
            deploy_type?: ("cloud" | "on_prem" | "hybrid") | null;
            /** Doc Url */
            doc_url?: string | null;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "inactive";
        };
        /**
         * ProductDetail
         * @description Product + 內嵌全部 log_types（含 fields / parse_rule / samples）。
         */
        ProductDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Vendor Id
             * Format: uuid
             */
            vendor_id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Version */
            version: string | null;
            /** Description */
            description: string | null;
            /** Deploy Type */
            deploy_type: ("cloud" | "on_prem" | "hybrid") | null;
            /** Doc Url */
            doc_url: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Log Types */
            log_types: components["schemas"]["LogTypeDetail"][];
        };
        /** ProductRead */
        ProductRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Vendor Id
             * Format: uuid
             */
            vendor_id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Version */
            version: string | null;
            /** Description */
            description: string | null;
            /** Deploy Type */
            deploy_type: ("cloud" | "on_prem" | "hybrid") | null;
            /** Doc Url */
            doc_url: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProductUpdate */
        ProductUpdate: {
            /** Name */
            name?: string | null;
            /** Version */
            version?: string | null;
            /** Description */
            description?: string | null;
            /** Deploy Type */
            deploy_type?: ("cloud" | "on_prem" | "hybrid") | null;
            /** Doc Url */
            doc_url?: string | null;
            /** Status */
            status?: ("active" | "inactive") | null;
        };
        /** SampleLogCreate */
        SampleLogCreate: {
            /** Raw Log */
            raw_log: string;
            /**
             * Label
             * @default normal
             * @enum {string}
             */
            label: "normal" | "edge_case" | "error";
            /** Description */
            description?: string | null;
        };
        /** SampleLogRead */
        SampleLogRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Log Type Id
             * Format: uuid
             */
            log_type_id: string;
            /** Raw Log */
            raw_log: string;
            /**
             * Label
             * @enum {string}
             */
            label: "normal" | "edge_case" | "error";
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StatsTotals */
        StatsTotals: {
            /** Total */
            total: number;
            /** Success */
            success: number;
            /** Error */
            error: number;
            /** Success Rate */
            success_rate: number;
        };
        /** TimelinePoint */
        TimelinePoint: {
            /** Day */
            day: string;
            /** Total */
            total: number;
            /** Success */
            success: number;
            /** Error */
            error: number;
            /** Success Rate */
            success_rate: number;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VendorCreate */
        VendorCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
            /** Website Url */
            website_url?: string | null;
            /** Logo Url */
            logo_url?: string | null;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "inactive";
        };
        /** VendorRead */
        VendorRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Website Url */
            website_url: string | null;
            /** Logo Url */
            logo_url: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** VendorUpdate */
        VendorUpdate: {
            /** Name */
            name?: string | null;
            /** Website Url */
            website_url?: string | null;
            /** Logo Url */
            logo_url?: string | null;
            /** Status */
            status?: ("active" | "inactive") | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_UserRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v1_library_overview_get: {
        parameters: {
            query?: {
                status?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_list_OverviewVendorGroup__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vendors_api_v1_library_vendors_get: {
        parameters: {
            query?: {
                status_filter?: ("active" | "inactive") | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_list_VendorRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vendor_api_v1_library_vendors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VendorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_VendorRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vendor_api_v1_library_vendors__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_VendorRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_vendor_api_v1_library_vendors__vendor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vendor_api_v1_library_vendors__vendor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VendorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_VendorRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_v1_library_vendors__vendor_slug__products_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor_slug: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_list_ProductRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_v1_library_vendors__vendor_slug__products_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor_slug: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ProductRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_v1_library_vendors__vendor_slug__products__product_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor_slug: string;
                product_slug: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ProductDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_product_api_v1_library_products__product_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_v1_library_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ProductRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_log_types_api_v1_library_products__product_id__log_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_list_LogTypeRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_log_type_api_v1_library_products__product_id__log_types_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogTypeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_LogTypeRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_log_type_api_v1_library_log_types__log_type_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_type_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_LogTypeDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_log_type_api_v1_library_log_types__log_type_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_type_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_log_type_api_v1_library_log_types__log_type_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_type_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogTypeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_LogTypeRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_log_type_api_v1_library_log_types__log_type_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_type_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_LogTypeRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_parse_rules_api_v1_library_log_types__log_type_id__parse_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_type_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_list_ParseRuleRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_parse_rule_draft_api_v1_library_log_types__log_type_id__parse_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_type_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ParseRuleRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_parse_rule_api_v1_library_parse_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ParseRuleRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_parse_rule_api_v1_library_parse_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ParseRuleRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_parse_rule_api_v1_library_parse_rules__rule_id__promote_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ParseRuleRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_log_type_fields_api_v1_library_log_types__log_type_id__fields_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_type_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldSchemaBulkReplace"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_list_FieldSchemaRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_samples_api_v1_library_log_types__log_type_id__samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_type_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_list_SampleLogRead__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_sample_api_v1_library_log_types__log_type_id__samples_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_type_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_SampleLogRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sample_api_v1_library_samples__sample_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_type_stats_api_v1_library_log_types__log_type_id__stats_get: {
        parameters: {
            query?: {
                range?: "7d" | "14d" | "30d" | "90d";
            };
            header?: never;
            path: {
                log_type_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_LogTypeStats_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_coverage_api_v1_library_products__vendor_slug___product_slug__coverage_get: {
        parameters: {
            query?: {
                range?: "7d" | "14d" | "30d" | "90d";
            };
            header?: never;
            path: {
                vendor_slug: string;
                product_slug: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ProductCoverage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_api_v1_analyzer_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ParseResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fixtures_api_v1_analyzer_fixtures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_FixtureListResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_api_v1_analyzer_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_CheckResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_availability_api_v1_analyzer_match_availability_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_MatchAvailabilityResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_api_v1_analyzer_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_MatchResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
